import { CountriesListType } from "./types";
export const all_countries: CountriesListType[] = [
  { name: "Afghanistan", shortName: "AF" },
  { name: "Albania", shortName: "AL" },
  { name: "Algeria", shortName: "DZ" },
  { name: "Andorra", shortName: "AD" },
  { name: "Angola", shortName: "AO" },
  { name: "Antigua and Barbuda", shortName: "AG" },
  { name: "Argentina", shortName: "AR" },
  { name: "Armenia", shortName: "AM" },
  { name: "Australia", shortName: "AU" },
  { name: "Austria", shortName: "AT" },
  { name: "Azerbaijan", shortName: "AZ" },
  { name: "Bahamas", shortName: "BS" },
  { name: "Bahrain", shortName: "BH" },
  { name: "Bangladesh", shortName: "BD" },
  { name: "Barbados", shortName: "BB" },
  { name: "Belarus", shortName: "BY" },
  { name: "Belgium", shortName: "BE" },
  { name: "Belize", shortName: "BZ" },
  { name: "Benin", shortName: "BJ" },
  { name: "Bhutan", shortName: "BT" },
  { name: "Bolivia", shortName: "BO" },
  { name: "Bosnia and Herzegovina", shortName: "BA" },
  { name: "Botswana", shortName: "BW" },
  { name: "Brazil", shortName: "BR" },
  { name: "Brunei Darussalam", shortName: "BN" },
  { name: "Bulgaria", shortName: "BG" },
  { name: "Burkina Faso", shortName: "BF" },
  { name: "Burundi", shortName: "BI" },
  { name: "Cabo Verde", shortName: "CV" },
  { name: "Cambodia", shortName: "KH" },
  { name: "Cameroon", shortName: "CM" },
  { name: "Canada", shortName: "CA" },
  { name: "Central African Republic", shortName: "CF" },
  { name: "Chad", shortName: "TD" },
  { name: "Chile", shortName: "CL" },
  { name: "China", shortName: "CN" },
  { name: "Colombia", shortName: "CO" },
  { name: "Comoros", shortName: "KM" },
  { name: "Congo, Democratic Republic of the", shortName: "CD" },
  { name: "Congo", shortName: "CG" },
  { name: "Costa Rica", shortName: "CR" },
  { name: "Côte d'Ivoire", shortName: "CI" },
  { name: "Croatia", shortName: "HR" },
  { name: "Cuba", shortName: "CU" },
  { name: "Cyprus", shortName: "CY" },
  { name: "Czech Republic", shortName: "CZ" },
  { name: "Denmark", shortName: "DK" },
  { name: "Djibouti", shortName: "DJ" },
  { name: "Dominica", shortName: "DM" },
  { name: "Dominican Republic", shortName: "DO" },
  { name: "Timor-Leste", shortName: "TL" },
  { name: "Ecuador", shortName: "EC" },
  { name: "Egypt", shortName: "EG" },
  { name: "El Salvador", shortName: "SV" },
  { name: "Equatorial Guinea", shortName: "GQ" },
  { name: "Eritrea", shortName: "ER" },
  { name: "Estonia", shortName: "EE" },
  { name: "Eswatini", shortName: "SZ" },
  { name: "Ethiopia", shortName: "ET" },
  { name: "Fiji", shortName: "FJ" },
  { name: "Finland", shortName: "FI" },
  { name: "France", shortName: "FR" },
  { name: "Gabon", shortName: "GA" },
  { name: "Gambia", shortName: "GM" },
  { name: "Georgia", shortName: "GE" },
  { name: "Germany", shortName: "DE" },
  { name: "Ghana", shortName: "GH" },
  { name: "Greece", shortName: "GR" },
  { name: "Grenada", shortName: "GD" },
  { name: "Guatemala", shortName: "GT" },
  { name: "Guinea", shortName: "GN" },
  { name: "Guinea-Bissau", shortName: "GW" },
  { name: "Guyana", shortName: "GY" },
  { name: "Haiti", shortName: "HT" },
  { name: "Honduras", shortName: "HN" },
  { name: "Hungary", shortName: "HU" },
  { name: "Iceland", shortName: "IS" },
  { name: "India", shortName: "IN" },
  { name: "Indonesia", shortName: "ID" },
  { name: "Iran", shortName: "IR" },
  { name: "Iraq", shortName: "IQ" },
  { name: "Ireland", shortName: "IE" },
  { name: "Israel", shortName: "IL" },
  { name: "Italy", shortName: "IT" },
  { name: "Jamaica", shortName: "JM" },
  { name: "Japan", shortName: "JP" },
  { name: "Jordan", shortName: "JO" },
  { name: "Kazakhstan", shortName: "KZ" },
  { name: "Kenya", shortName: "KE" },
  { name: "Kiribati", shortName: "KI" },
  { name: "South Korea", shortName: "KP" },
  { name: "North Korea", shortName: "KR" },
  { name: "Kosovo", shortName: "XK" },
  { name: "Kuwait", shortName: "KW" },
  { name: "Kyrgyzstan", shortName: "KG" },
  { name: "Lao People's Democratic Republic", shortName: "LA" },
  { name: "Latvia", shortName: "LV" },
  { name: "Lebanon", shortName: "LB" },
  { name: "Lesotho", shortName: "LS" },
  { name: "Liberia", shortName: "LR" },
  { name: "Libya", shortName: "LY" },
  { name: "Liechtenstein", shortName: "LI" },
  { name: "Lithuania", shortName: "LT" },
  { name: "Luxembourg", shortName: "LU" },
  { name: "Madagascar", shortName: "MG" },
  { name: "Malawi", shortName: "MW" },
  { name: "Malaysia", shortName: "MY" },
  { name: "Maldives", shortName: "MV" },
  { name: "Mali", shortName: "ML" },
  { name: "Malta", shortName: "MT" },
  { name: "Marshall Islands", shortName: "MH" },
  { name: "Mauritania", shortName: "MR" },
  { name: "Mauritius", shortName: "MU" },
  { name: "Mexico", shortName: "MX" },
  { name: "Micronesia (Federated States of)", shortName: "FM" },
  { name: "Moldova", shortName: "MD" },
  { name: "Monaco", shortName: "MC" },
  { name: "Mongolia", shortName: "MN" },
  { name: "Montenegro", shortName: "ME" },
  { name: "Morocco", shortName: "MA" },
  { name: "Mozambique", shortName: "MZ" },
  { name: "Myanmar", shortName: "MM" },
  { name: "Namibia", shortName: "NA" },
  { name: "Nauru", shortName: "NR" },
  { name: "Nepal", shortName: "NP" },
  { name: "Netherlands", shortName: "NL" },
  { name: "New Zealand", shortName: "NZ" },
  { name: "Nicaragua", shortName: "NI" },
  { name: "Niger", shortName: "NE" },
  { name: "Nigeria", shortName: "NG" },
  { name: "North Macedonia", shortName: "MK" },
  { name: "Norway", shortName: "NO" },
  { name: "Oman", shortName: "OM" },
  { name: "Pakistan", shortName: "PK" },
  { name: "Palau", shortName: "PW" },
  { name: "Panama", shortName: "PA" },
  { name: "Papua New Guinea", shortName: "PG" },
  { name: "Paraguay", shortName: "PY" },
  { name: "Peru", shortName: "PE" },
  { name: "Philippines", shortName: "PH" },
  { name: "Poland", shortName: "PL" },
  { name: "Portugal", shortName: "PT" },
  { name: "Qatar", shortName: "QA" },
  { name: "Romania", shortName: "RO" },
  { name: "Russia", shortName: "RU" },
  { name: "Rwanda", shortName: "RW" },
  { name: "Saint Kitts and Nevis", shortName: "KN" },
  { name: "Saint Lucia", shortName: "LC" },
  { name: "Saint Vincent and the Grenadines", shortName: "VC" },
  { name: "Samoa", shortName: "WS" },
  { name: "San Marino", shortName: "SM" },
  { name: "Sao Tome and Principe", shortName: "ST" },
  { name: "Saudi Arabia", shortName: "SA" },
  { name: "Senegal", shortName: "SN" },
  { name: "Serbia", shortName: "RS" },
  { name: "Seychelles", shortName: "SC" },
  { name: "Sierra Leone", shortName: "SL" },
  { name: "Singapore", shortName: "SG" },
  { name: "Slovakia", shortName: "SK" },
  { name: "Slovenia", shortName: "SI" },
  { name: "Solomon Islands", shortName: "SB" },
  { name: "Somalia", shortName: "SO" },
  { name: "South Africa", shortName: "ZA" },
  { name: "Spain", shortName: "ES" },
  { name: "Sri Lanka", shortName: "LK" },
  { name: "Sudan", shortName: "SD" },
  { name: "South Sudan", shortName: "SS" },
  { name: "Suriname", shortName: "SR" },
  { name: "Sweden", shortName: "SE" },
  { name: "Switzerland", shortName: "CH" },
  { name: "Syria", shortName: "SY" },
  { name: "Taiwan", shortName: "TW" },
  { name: "Tajikistan", shortName: "TJ" },
  { name: "Thailand", shortName: "TH" },
  { name: "Togo", shortName: "TG" },
  { name: "Tonga", shortName: "TO" },
  { name: "Trinidad and Tobago", shortName: "TT" },
  { name: "Tunisia", shortName: "TN" },
  { name: "Turkey", shortName: "TR" },
  { name: "Turkmenistan", shortName: "TM" },
  { name: "Tuvalu", shortName: "TV" },
  { name: "Uganda", shortName: "UG" },
  { name: "Ukraine", shortName: "UA" },
  { name: "United Arab Emirates", shortName: "AE" },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    shortName: "GB",
  },
  { name: "United States of America", shortName: "US" },
  { name: "Uruguay", shortName: "UY" },
  { name: "Uzbekistan", shortName: "UZ" },
  { name: "Vanuatu", shortName: "VU" },
  { name: "Venezuela", shortName: "VE" },
  { name: "VietNam", shortName: "VN" },
  { name: "Yemen", shortName: "YE" },
  { name: "Zambia", shortName: "ZM" },
  { name: "Zimbabwe", shortName: "ZW" },
];
